import 'dart:async';

import 'package:fireplace/fireplace_services.dart';
import 'package:fireplace/src/app/providers.dart';
import 'package:fireplace/src/model/chat/message_limits.dart';
import 'package:fireplace/src/styles/theme.dart';
import 'package:fireplace/src/ui/chat_activity.dart';
import 'package:fireplace/src/view/chat/chat_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/misc.dart' show Override;
import 'package:flutter_test/flutter_test.dart';

import '../../support/ui_fixture.dart';
import 'send_action_feedback_test.dart' show ActionChat;

const cases = [
  'normal',
  'empty',
  'blocked',
  'incoming',
  'waiting',
  'outgoing',
  'identity',
  'unconfirmed',
  'send error',
  'search',
  'history error',
  'loading',
  'account changed',
  'privacy error',
  'draft',
  'counter',
  'large text keyboard',
  'open menu',
  'scrolled',
];

// Framework-generated key identities vary between runs. Preserve their type,
// debug label and multiplicity, while discarding only the identity hash.
String stableKey(Key key) =>
    key.toString().replaceAll(RegExp(r'#[0-9a-f]{5}'), '#identity');

Map<String, List<String>> inventory(WidgetTester t) {
  final keys = <String>[], texts = <String>[], semantics = <String>[];
  for (final e in t.allElements) {
    final w = e.widget;
    if (w.key != null) keys.add(stableKey(w.key!));
    if (w is Text) texts.add(w.data ?? w.textSpan!.toPlainText());
    if (w is Semantics) {
      if (w.properties.label != null) {
        semantics.add('label: ${w.properties.label}');
      }
      if (w.properties.tooltip != null) {
        semantics.add('tooltip: ${w.properties.tooltip}');
      }
    }
    if (w is Tooltip) {
      semantics.add('tooltip: ${w.message ?? w.richMessage!.toPlainText()}');
    }
  }
  return {
    'keys': keys..sort(),
    'texts': texts..sort(),
    'semantics': semantics..sort(),
  };
}

Future<UiFixture> mount(WidgetTester t, String state) async {
  final f = UiFixture(
    chat: ActionChat()..checkError = StateError('check unavailable'),
  );
  addTearDown(f.session.close);
  if (!['empty', 'loading', 'incoming'].contains(state)) await f.seed();
  if (state == 'blocked') f.blocked = {'fred'};
  if (state == 'identity') f.alerts = {'fred': List.generate(64, (i) => i)};
  if (['incoming', 'waiting', 'outgoing'].contains(state)) {
    f.chat.summaries = [
      ChatSummary(
        'alice_fred',
        'fred',
        fixtureTime,
        initiator: state == 'incoming' ? 'fred' : 'alice',
        accepted: false,
        requestCount: state == 'waiting' ? ChatService.requestLimit : 1,
      ),
    ];
  }
  if (state == 'unconfirmed') {
    await f.chat.store.add(
      message(
        id: 'uncertain',
        body: 'Please check this message',
        outgoing: true,
        status: MessageStatus.unconfirmed,
        at: fixtureTime.add(const Duration(minutes: 1)),
      ),
    );
  }
  if (state == 'scrolled') {
    for (var i = 0; i < 30; i++) {
      await f.chat.store.add(
        message(
          id: 'long-$i',
          body: 'History message $i',
          at: fixtureTime.add(Duration(minutes: i + 1)),
        ),
      );
    }
  }
  final extra = <Override>[
    if (state == 'account changed')
      appSessionProvider.overrideWithValue(const AsyncData(null)),
    if (state == 'privacy error')
      blockedUidsProvider.overrideWith(
        (ref) => Stream.error(StateError('privacy')),
      ),
    if (state == 'history error')
      messagesProvider('alice_fred')
          .overrideWith((ref) => Stream.error(StateError('history'))),
    if (state == 'loading')
      messagesProvider('alice_fred')
          .overrideWith((ref) => const Stream.empty()),
  ];
  await t.pumpWidget(
    ProviderScope(
      overrides: [
        for (final o in f.overrides)
          if (!extra.any((e) => e.origin == o.origin)) o,
        ...extra,
      ],
      child: MaterialApp(
        theme: fireplaceTheme(Brightness.light),
        navigatorObservers: [chatRouteObserver],
        builder: (context, child) => MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaler: TextScaler.linear(
              state == 'large text keyboard' ? 2 : 1,
            ),
            viewInsets: EdgeInsets.only(
              bottom: state == 'large text keyboard' ? 260 : 0,
            ),
          ),
          child: child!,
        ),
        home: ChatScreen(
          chatId: 'alice_fred',
          initialMessageId: state == 'search' ? '3' : null,
        ),
      ),
    ),
  );
  await settleUi(t);
  if (['draft', 'counter', 'send error'].contains(state)) {
    await t.enterText(
      find.byKey(const Key('composer')),
      state == 'counter'
          ? 'x' * (maxMessageCharacters * .9).floor()
          : state == 'draft'
          ? 'x' * 120
          : 'hello',
    );
    await t.pump();
  }
  if (state == 'send error') {
    f.chat.sendError = ChatException('Send refused');
    await t.tap(find.byKey(const Key('send')));
    await settleUi(t);
  }
  if (state == 'unconfirmed') {
    await t.tap(find.byKey(const Key('checkSendStatus')));
    await settleUi(t);
    expect(find.byKey(const Key('checkNote')), findsOneWidget);
  }
  if (state == 'open menu') {
    await t.tap(find.byKey(const Key('chatMenu')));
    await t.pumpAndSettle();
  }
  if (state == 'scrolled') {
    t
        .widget<ListView>(find.byKey(const Key('messageTimeline')))
        .controller!
        .jumpTo(400);
    await t.pumpAndSettle();
  }
  return f;
}

void main() {
  for (final state in cases) {
    testWidgets('chat inventory: $state', (t) async {
      await mount(t, state);
      expect(t.takeException(), isNull);
      final actual = inventory(t);
      expect(actual, expected[state], reason: state);
    });
  }
  for (final meta in [false, true]) {
    testWidgets('chat shortcut ${meta ? "Meta" : "Ctrl"}+Enter sends', (
      t,
    ) async {
      final f = await mount(t, 'empty');
      await t.enterText(find.byKey(const Key('composer')), 'hello');
      await t.pump();
      final modifier = meta
          ? LogicalKeyboardKey.metaLeft
          : LogicalKeyboardKey.controlLeft;
      await t.sendKeyDownEvent(modifier);
      await t.sendKeyEvent(LogicalKeyboardKey.enter);
      await t.sendKeyUpEvent(modifier);
      await settleUi(t);
      expect(f.chat.sends, ['hello']);
    });
  }
  testWidgets('typing enables send and counter starts at ninety percent', (
    t,
  ) async {
    await mount(t, 'empty');
    IconButton send() => t.widget<IconButton>(find.byKey(const Key('send')));
    expect(send().onPressed, isNull);
    final threshold = (maxMessageCharacters * .9).floor();
    await t.enterText(find.byKey(const Key('composer')), 'x' * (threshold - 1));
    await t.pump();
    expect(send().onPressed, isNotNull);
    expect(find.byKey(const Key('messageCounter')), findsNothing);
    await t.enterText(find.byKey(const Key('composer')), 'x' * threshold);
    await t.pump();
    expect(find.text('$threshold / 16,384'), findsOneWidget);
  });
}

// Recorded on unchanged main 9d9d0f3; keep frozen through this extraction.
const expected = <String, Map<String, List<String>>>{
  'normal': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'empty': {
    'keys': [
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      'A private conversation',
      'F',
      'Message',
      'Messages are end-to-end encrypted. Say hello when you’re ready.',
      'fred',
    ],
    'semantics': [
      'label: Back',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'blocked': {
    'keys': [
      '[<\'blockedNote\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      'Conversation hidden',
      'F',
      'Unblock',
      'Unblock this contact in Settings to see your history again.',
      'You blocked @fred.',
      'fred',
    ],
    'semantics': [
      'label: Back',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'incoming': {
    'keys': [
      '[<\'acceptRequest\'>]',
      '[<\'acceptToReplyNote\'>]',
      '[<\'blockRequest\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'reportRequest\'>]',
      '[<\'requestBanner\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '@fred wants to chat. You will not see their messages until you accept. They will not be told whether you looked.',
      'A new message request',
      'Accept',
      'Accept this request to reply.',
      'Block',
      'F',
      'Messages stay hidden until you accept.',
      'Report',
      'fred',
    ],
    'semantics': [
      'label: Back',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'waiting': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'verify\'>]',
      '[<\'waitingNote\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'Waiting for @fred to accept your request.',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'outgoing': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'requestSentNote\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Message request sent. @fred sees it once they accept (2 left).',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'identity': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'identityBanner\'>]',
      '[<\'identityHeldNote\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'reviewIdentity\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      '@fred\'s security code changed. Messages are on hold until you review it.',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Review',
      'Review this contact’s security code before sending.',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'unconfirmed': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'checkNote\'>]',
      '[<\'checkSendStatus\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageBubble-uncertain\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'resendUnconfirmed\'>]',
      '[<\'send\'>]',
      '[<\'uncertain\'>]',
      '[<\'unconfirmed-uncertain\'>]',
      '[<\'unconfirmedTitle\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[Key <[<\'uncertain\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      '12:01 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'Check status',
      'Could not check yet. Nothing was sent again. Try later.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Message not confirmed',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Please check this message',
      'Sat, Oct 3',
      'Send again…',
      'Sun, Oct 4',
      'This message may have reached them. Sending it again could create a duplicate.',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: Please check this message',
      'label: You',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'send error': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'sendFailure\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'Dismiss',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Send refused',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'search': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'searchLocation\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'F',
      'Message',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Search result — showing messages up to this point.',
      'Show latest messages',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Back',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'history error': {
    'keys': [
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      'Could not load history',
      'F',
      'Message',
      'Try again',
      'Try again to read the history on this device.',
      'fred',
    ],
    'semantics': [
      'label: Back',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'loading': {
    'keys': [
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': ['F', 'Message', 'fred'],
    'semantics': [
      'label: Back',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'account changed': {
    'keys': [
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.middle>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      'Conversation unavailable',
      'Return to chats',
      'Return to your chats',
      'Your account changed or is not ready. Open the conversation again from your chat list.',
    ],
    'semantics': [],
  },
  'privacy error': {
    'keys': [
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.middle>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      'Conversation',
      'Could not load privacy settings',
      'Try again',
      'Your conversation stays hidden until these settings are available.',
    ],
    'semantics': [],
  },
  'draft': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'counter': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageCounter\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      '14745 / 16,384',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'large text keyboard': {
    'keys': [
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      'Around two? There is no rush.',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Perfect. See you in the garden ☕',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Looking forward to it. What time works for you?',
      'label: Perfect. See you in the garden ☕',
      'label: You',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'open menu': {
    'keys': [
      '[<\'1\'>]',
      '[<\'2\'>]',
      '[<\'3\'>]',
      '[<\'4\'>]',
      '[<\'5\'>]',
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'menuBlock\'>]',
      '[<\'menuMute\'>]',
      '[<\'menuReport\'>]',
      '[<\'messageBubble-1\'>]',
      '[<\'messageBubble-2\'>]',
      '[<\'messageBubble-3\'>]',
      '[<\'messageBubble-4\'>]',
      '[<\'messageBubble-5\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'1\'>]>]',
      '[Key <[<\'2\'>]>]',
      '[Key <[<\'3\'>]>]',
      '[Key <[<\'4\'>]>]',
      '[Key <[<\'5\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<String?>>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '11:52 AM',
      '11:56 AM',
      '12:00 PM',
      '12:00 PM',
      '12:00 PM',
      'Are we still on for Saturday?',
      'Around two? There is no rush.',
      'Block',
      'F',
      'Looking forward to it. What time works for you?',
      'Message',
      'Mute chat',
      'Of course. I can bring dessert.',
      'Perfect. See you in the garden ☕',
      'Report',
      'Sat, Oct 3',
      'Sun, Oct 4',
      'fred',
    ],
    'semantics': [
      'label: Are we still on for Saturday?',
      'label: Around two? There is no rush.',
      'label: Back',
      'label: Dismiss menu',
      'label: Looking forward to it. What time works for you?',
      'label: Of course. I can bring dessert.',
      'label: Perfect. See you in the garden ☕',
      'label: Popup menu',
      'label: You',
      'label: You',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
  'scrolled': {
    'keys': [
      '[<\'chatBack\'>]',
      '[<\'chatDetails\'>]',
      '[<\'chatMenu\'>]',
      '[<\'chatSafetyNotices\'>]',
      '[<\'composer\'>]',
      '[<\'latestMessages\'>]',
      '[<\'long-12\'>]',
      '[<\'long-13\'>]',
      '[<\'long-14\'>]',
      '[<\'long-15\'>]',
      '[<\'long-16\'>]',
      '[<\'long-17\'>]',
      '[<\'long-18\'>]',
      '[<\'long-19\'>]',
      '[<\'long-20\'>]',
      '[<\'long-21\'>]',
      '[<\'long-22\'>]',
      '[<\'long-23\'>]',
      '[<\'long-24\'>]',
      '[<\'long-25\'>]',
      '[<\'long-26\'>]',
      '[<\'long-27\'>]',
      '[<\'messageBubble-long-12\'>]',
      '[<\'messageBubble-long-13\'>]',
      '[<\'messageBubble-long-14\'>]',
      '[<\'messageBubble-long-15\'>]',
      '[<\'messageBubble-long-16\'>]',
      '[<\'messageBubble-long-17\'>]',
      '[<\'messageBubble-long-18\'>]',
      '[<\'messageBubble-long-19\'>]',
      '[<\'messageBubble-long-20\'>]',
      '[<\'messageBubble-long-21\'>]',
      '[<\'messageBubble-long-22\'>]',
      '[<\'messageBubble-long-23\'>]',
      '[<\'messageBubble-long-24\'>]',
      '[<\'messageBubble-long-25\'>]',
      '[<\'messageBubble-long-26\'>]',
      '[<\'messageBubble-long-27\'>]',
      '[<\'messageTimeline\'>]',
      '[<\'send\'>]',
      '[<\'verify\'>]',
      '[<StandardComponentType.moreButton>]',
      '[<_ScaffoldSlot.appBar>]',
      '[<_ScaffoldSlot.body>]',
      '[<_ScaffoldSlot.floatingActionButton>]',
      '[<_ToolbarSlot.leading>]',
      '[<_ToolbarSlot.middle>]',
      '[<_ToolbarSlot.trailing>]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity ink renderer]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalKey#identity]',
      '[GlobalObjectKey _MaterialAppState#identity]',
      '[GlobalObjectKey<NavigatorState> _WidgetsAppState#identity]',
      '[Key <[<\'long-12\'>]>]',
      '[Key <[<\'long-13\'>]>]',
      '[Key <[<\'long-14\'>]>]',
      '[Key <[<\'long-15\'>]>]',
      '[Key <[<\'long-16\'>]>]',
      '[Key <[<\'long-17\'>]>]',
      '[Key <[<\'long-18\'>]>]',
      '[Key <[<\'long-19\'>]>]',
      '[Key <[<\'long-20\'>]>]',
      '[Key <[<\'long-21\'>]>]',
      '[Key <[<\'long-22\'>]>]',
      '[Key <[<\'long-23\'>]>]',
      '[Key <[<\'long-24\'>]>]',
      '[Key <[<\'long-25\'>]>]',
      '[Key <[<\'long-26\'>]>]',
      '[Key <[<\'long-27\'>]>]',
      '[LabeledGlobalKey<EditableTextState>#identity]',
      '[LabeledGlobalKey<OverlayState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawGestureDetectorState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<RawTooltipState>#identity]',
      '[LabeledGlobalKey<_ModalScopeState<dynamic>>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[LabeledGlobalKey<_OverlayEntryWidgetState>#identity]',
      '[_DeprecatedRawViewKey TestFlutterView#identity]',
    ],
    'texts': [
      '12:13 PM',
      '12:14 PM',
      '12:15 PM',
      '12:16 PM',
      '12:17 PM',
      '12:18 PM',
      '12:19 PM',
      '12:20 PM',
      '12:21 PM',
      '12:22 PM',
      '12:23 PM',
      '12:24 PM',
      '12:25 PM',
      '12:26 PM',
      '12:27 PM',
      '12:28 PM',
      'F',
      'History message 12',
      'History message 13',
      'History message 14',
      'History message 15',
      'History message 16',
      'History message 17',
      'History message 18',
      'History message 19',
      'History message 20',
      'History message 21',
      'History message 22',
      'History message 23',
      'History message 24',
      'History message 25',
      'History message 26',
      'History message 27',
      'Latest messages',
      'Message',
      'fred',
    ],
    'semantics': [
      'label: Back',
      'label: History message 12',
      'label: History message 13',
      'label: History message 14',
      'label: History message 15',
      'label: History message 16',
      'label: History message 17',
      'label: History message 18',
      'label: History message 19',
      'label: History message 20',
      'label: History message 21',
      'label: History message 22',
      'label: History message 23',
      'label: History message 24',
      'label: History message 25',
      'label: History message 26',
      'label: History message 27',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'label: fred',
      'tooltip: Back to chats',
      'tooltip: Back to chats',
      'tooltip: Send message',
      'tooltip: Send message',
      'tooltip: Show menu',
      'tooltip: Show menu',
      'tooltip: Verify security code',
      'tooltip: Verify security code',
    ],
  },
};
